<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>callieandgrant.com</title>
	<link rel="stylesheet" type="text/css" href="css/main.css">
	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oxygen:700,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'>
</head>

<header>
	<div id="chevron">
	</div>
	<nav>
		<ul>
			<li><a href="story.php">our story</a></li>
			<li><a href="day.php">our day</a></li>
			<li><a class="logo" href="index.php"><img src="img/logo.png" alt="Home"/></a></li>
			<li><a href="guests.php">our guests</a></li>
			<li><a href="login.php">login</a></li>
		</ul>
	</nav>
</header>
